version: '3.9'

services:
  cardano-explorer-fe:
    stdin_open: true
    container_name: cardano-explorer-fe
    image: cardano-explorer-fe
    build:
      context: .
    environment:
      - PORT=${PORT:-3000}
      - REACT_APP_TESTNET_API_URL=${REACT_APP_TESTNET_API_URL}
      - REACT_APP_PREVIEW_API_URL=${REACT_APP_PREVIEW_API_URL}
      - REACT_APP_PREPROD_API_URL=${REACT_APP_PREPROD_API_URL}
      - REACT_APP_MAINNET_API_URL=${REACT_APP_MAINNET_API_URL} 
      - REACT_APP_AUTH_API_URL=${REACT_APP_AUTH_API_URL}
    ports:
      - "9296:${PORT:-3000}"
