version: '3.9'
networks:
  default:
    name: infrastructure-net
    external: true

services:
  cardano-explorer-fe-test:
    stdin_open: true
    container_name: cardano-explorer-fe-test
    image: cardano-explorer-fe-test
    build:
      context: .
    environment:
      - PORT=${PORT}
      - REACT_APP_NETWORK=${REACT_APP_NETWORK}
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_AUTH_API_URL=${REACT_APP_AUTH_API_URL}
    ports:
      - '7276:1102'