FROM node:16 as build

WORKDIR /app

COPY package*.json /app/
RUN npm ci
COPY . .

ARG REACT_APP_API_URL
ARG REACT_APP_AUTH_API_URL
ARG REACT_APP_JSD_WIDGET_KEY
ARG REACT_APP_NETWORK
ARG REACT_APP_MAINNET_APP_URL
ARG REACT_APP_PREPROD_APP_URL
ARG REACT_APP_PREVIEW_APP_URL
ARG REACT_APP_TESTNET_APP_URL

ENV REACT_APP_API_URL $REACT_APP_API_URL
ENV REACT_APP_AUTH_API_URL $REACT_APP_AUTH_API_URL
ENV REACT_APP_JSD_WIDGET_KEY $REACT_APP_JSD_WIDGET_KEY
ENV REACT_APP_NETWORK $REACT_APP_NETWORK
ENV REACT_APP_MAINNET_APP_URL $REACT_APP_MAINNET_APP_URL
ENV REACT_APP_PREPROD_APP_URL $REACT_APP_PREPROD_APP_URL
ENV REACT_APP_PREVIEW_APP_URL $REACT_APP_PREVIEW_APP_URL
ENV REACT_APP_TESTNET_APP_URL $REACT_APP_TESTNET_APP_URL
RUN npm run build

FROM nginx:1.19.6-alpine

COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
