version: '3.9'

services:
  cardano-explorer-fe:
    stdin_open: true
    image: cardano-explorer-fe
    build:
      context: .
    environment:
      - REACT_APP_TESTNET_API_URL=${REACT_APP_TESTNET_API_URL}
      - REACT_APP_PREVIEW_API_URL=${REACT_APP_PREVIEW_API_URL}
      - REACT_APP_PREPROD_API_URL=${REACT_APP_PREPROD_API_URL}
      - REACT_APP_MAINNET_API_URL=${REACT_APP_MAINNET_API_URL}
      - REACT_APP_AUTH_API_URL=${REACT_APP_AUTH_API_URL}
    ports:
      - '7276:80'
