/* eslint-disable no-undef */
window.env = {};
window.env.REACT_APP_VERSION = `$REACT_APP_VERSION`;
window.env.REACT_APP_NETWORK = `$REACT_APP_NETWORK`;
window.env.REACT_APP_API_URL = `$REACT_APP_API_URL`;
window.env.REACT_APP_WS_URL = `$REACT_APP_WS_URL`;

window.env.REACT_APP_AUTH_API_URL = `$REACT_APP_AUTH_API_URL`;

window.env.REACT_APP_JSD_WIDGET_KEY = `$REACT_APP_JSD_WIDGET_KEY`;
window.env.REACT_APP_MAINNET_APP_URL = `$REACT_APP_MAINNET_APP_URL`;
window.env.REACT_APP_PREPROD_APP_URL = `$REACT_APP_PREPROD_APP_URL`;
window.env.REACT_APP_PREVIEW_APP_URL = `$REACT_APP_PREVIEW_APP_URL`;
window.env.REACT_APP_TESTNET_APP_URL = `$REACT_APP_TESTNET_APP_URL`;
window.env.REACT_APP_SANCHONET_APP_URL = `$REACT_APP_SANCHONET_APP_URL`;

window.env.REACT_APP_EXT_ADA_PRICE_URL = `$REACT_APP_EXT_ADA_PRICE_URL`;
window.env.REACT_APP_NETWORK_NAMES = `$REACT_APP_NETWORK_NAMES`;
window.env.REACT_APP_CARDANO_NEWS_URL = `$REACT_APP_CARDANO_NEWS_URL`;
window.env.REACT_APP_ADA_HANDLE_API = `$REACT_APP_ADA_HANDLE_API`;
window.env.REACT_APP_BOLNISI_NAME_API = `$REACT_APP_BOLNISI_NAME_API`;
window.env.REACT_APP_API_URL_COIN_GECKKO = `$REACT_APP_API_URL_COIN_GECKKO`;
