/* tslint:disable */
/* eslint-disable */
/**
 * Yaci Store API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Amt } from "./amt";
/**
 *
 *
 * @export
 * @interface AddressBalanceDto
 */
export interface AddressBalanceDto {
  /**
   * @type {number}
   * @memberof AddressBalanceDto
   */
  blockNumber?: number;

  /**
   * @type {number}
   * @memberof AddressBalanceDto
   */
  blockTime?: number;

  /**
   * @type {string}
   * @memberof AddressBalanceDto
   */
  address?: string;

  /**
   * @type {Array<Amt>}
   * @memberof AddressBalanceDto
   */
  amounts?: Array<Amt>;

  /**
   * @type {number}
   * @memberof AddressBalanceDto
   */
  slot?: number;

  /**
   * @type {number}
   * @memberof AddressBalanceDto
   */
  lastBalanceCalculationBlock?: number;
}
