/* tslint:disable */
/* eslint-disable */
/**
 * Yaci Store API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Amt } from "./amt";
/**
 *
 *
 * @export
 * @interface AddressUtxo
 */
export interface AddressUtxo {
  /**
   * @type {number}
   * @memberof AddressUtxo
   */
  blockNumber?: number;

  /**
   * @type {number}
   * @memberof AddressUtxo
   */
  blockTime?: number;

  /**
   * @type {string}
   * @memberof AddressUtxo
   */
  txHash?: string;

  /**
   * @type {number}
   * @memberof AddressUtxo
   */
  outputIndex?: number;

  /**
   * @type {number}
   * @memberof AddressUtxo
   */
  slot?: number;

  /**
   * @type {string}
   * @memberof AddressUtxo
   */
  blockHash?: string;

  /**
   * @type {number}
   * @memberof AddressUtxo
   */
  epoch?: number;

  /**
   * @type {string}
   * @memberof AddressUtxo
   */
  ownerAddr?: string;

  /**
   * @type {string}
   * @memberof AddressUtxo
   */
  ownerStakeAddr?: string;

  /**
   * @type {string}
   * @memberof AddressUtxo
   */
  ownerPaymentCredential?: string;

  /**
   * @type {string}
   * @memberof AddressUtxo
   */
  ownerStakeCredential?: string;

  /**
   * @type {number}
   * @memberof AddressUtxo
   */
  lovelaceAmount?: number;

  /**
   * @type {Array<Amt>}
   * @memberof AddressUtxo
   */
  amounts?: Array<Amt>;

  /**
   * @type {string}
   * @memberof AddressUtxo
   */
  dataHash?: string;

  /**
   * @type {string}
   * @memberof AddressUtxo
   */
  inlineDatum?: string;

  /**
   * @type {string}
   * @memberof AddressUtxo
   */
  scriptRef?: string;

  /**
   * @type {string}
   * @memberof AddressUtxo
   */
  referenceScriptHash?: string;

  /**
   * @type {boolean}
   * @memberof AddressUtxo
   */
  isCollateralReturn?: boolean;
}
