/* tslint:disable */
/* eslint-disable */
/**
 * Yaci Store API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface Amt
 */
export interface Amt {
  /**
   * @type {string}
   * @memberof Amt
   */
  unit?: string;

  /**
   * @type {string}
   * @memberof Amt
   */
  policyId?: string;

  /**
   * @type {string}
   * @memberof Amt
   */
  assetName?: string;

  /**
   * @type {number}
   * @memberof Amt
   */
  quantity?: number;
}
