/* tslint:disable */
/* eslint-disable */
/**
 * Yaci Store API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { CommitteeMemberDto } from "./committee-member-dto";
/**
 *
 *
 * @export
 * @interface CommitteeDto
 */
export interface CommitteeDto {
  /**
   * @type {number}
   * @memberof CommitteeDto
   */
  thresholdNumerator?: number;

  /**
   * @type {number}
   * @memberof CommitteeDto
   */
  thresholdDenominator?: number;

  /**
   * @type {Array<CommitteeMemberDto>}
   * @memberof CommitteeDto
   */
  members?: Array<CommitteeMemberDto>;
}
