/* tslint:disable */
/* eslint-disable */
/**
 * Yaci Store API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface DelegationVote
 */
export interface DelegationVote {
  /**
   * @type {number}
   * @memberof DelegationVote
   */
  blockNumber?: number;

  /**
   * @type {number}
   * @memberof DelegationVote
   */
  blockTime?: number;

  /**
   * @type {string}
   * @memberof DelegationVote
   */
  txHash?: string;

  /**
   * @type {number}
   * @memberof DelegationVote
   */
  certIndex?: number;

  /**
   * @type {number}
   * @memberof DelegationVote
   */
  slot?: number;

  /**
   * @type {string}
   * @memberof DelegationVote
   */
  address?: string;

  /**
   * @type {string}
   * @memberof DelegationVote
   */
  drepHash?: string;

  /**
   * @type {string}
   * @memberof DelegationVote
   */
  drepId?: string;

  /**
   * @type {string}
   * @memberof DelegationVote
   */
  drepType?: DelegationVoteDrepTypeEnum;

  /**
   * @type {string}
   * @memberof DelegationVote
   */
  credential?: string;

  /**
   * @type {string}
   * @memberof DelegationVote
   */
  credType?: DelegationVoteCredTypeEnum;

  /**
   * @type {number}
   * @memberof DelegationVote
   */
  epoch?: number;
}

/**
 * @export
 * @enum {string}
 */
export enum DelegationVoteDrepTypeEnum {
  ADDRKEYHASH = "ADDR_KEYHASH",
  SCRIPTHASH = "SCRIPTHASH",
  ABSTAIN = "ABSTAIN",
  NOCONFIDENCE = "NO_CONFIDENCE"
}
/**
 * @export
 * @enum {string}
 */
export enum DelegationVoteCredTypeEnum {
  ADDRKEYHASH = "ADDR_KEYHASH",
  SCRIPTHASH = "SCRIPTHASH"
}
