/* tslint:disable */
/* eslint-disable */
/**
 * Yaci Store API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface DRepRegistration
 */
export interface DRepRegistration {
  /**
   * @type {number}
   * @memberof DRepRegistration
   */
  blockNumber?: number;

  /**
   * @type {number}
   * @memberof DRepRegistration
   */
  blockTime?: number;

  /**
   * @type {string}
   * @memberof DRepRegistration
   */
  txHash?: string;

  /**
   * @type {number}
   * @memberof DRepRegistration
   */
  certIndex?: number;

  /**
   * @type {string}
   * @memberof DRepRegistration
   */
  type?: DRepRegistrationTypeEnum;

  /**
   * @type {number}
   * @memberof DRepRegistration
   */
  slot?: number;

  /**
   * @type {number}
   * @memberof DRepRegistration
   */
  deposit?: number;

  /**
   * @type {string}
   * @memberof DRepRegistration
   */
  drepHash?: string;

  /**
   * @type {string}
   * @memberof DRepRegistration
   */
  drepId?: string;

  /**
   * @type {string}
   * @memberof DRepRegistration
   */
  anchorUrl?: string;

  /**
   * @type {string}
   * @memberof DRepRegistration
   */
  anchorHash?: string;

  /**
   * @type {string}
   * @memberof DRepRegistration
   */
  credType?: DRepRegistrationCredTypeEnum;

  /**
   * @type {number}
   * @memberof DRepRegistration
   */
  epoch?: number;
}

/**
 * @export
 * @enum {string}
 */
export enum DRepRegistrationTypeEnum {
  STAKEREGISTRATION = "STAKE_REGISTRATION",
  STAKEDEREGISTRATION = "STAKE_DEREGISTRATION",
  STAKEDELEGATION = "STAKE_DELEGATION",
  POOLREGISTRATION = "POOL_REGISTRATION",
  POOLRETIREMENT = "POOL_RETIREMENT",
  GENESISKEYDELEGATION = "GENESIS_KEY_DELEGATION",
  MOVEINSTATENEOUSREWARDSCERT = "MOVE_INSTATENEOUS_REWARDS_CERT",
  REGCERT = "REG_CERT",
  UNREGCERT = "UNREG_CERT",
  VOTEDELEGCERT = "VOTE_DELEG_CERT",
  STAKEVOTEDELEGCERT = "STAKE_VOTE_DELEG_CERT",
  STAKEREGDELEGCERT = "STAKE_REG_DELEG_CERT",
  VOTEREGDELEGCERT = "VOTE_REG_DELEG_CERT",
  STAKEVOTEREGDELEGCERT = "STAKE_VOTE_REG_DELEG_CERT",
  AUTHCOMMITTEEHOTCERT = "AUTH_COMMITTEE_HOT_CERT",
  RESIGNCOMMITTEECOLDCERT = "RESIGN_COMMITTEE_COLD_CERT",
  REGDREPCERT = "REG_DREP_CERT",
  UNREGDREPCERT = "UNREG_DREP_CERT",
  UPDATEDREPCERT = "UPDATE_DREP_CERT"
}
/**
 * @export
 * @enum {string}
 */
export enum DRepRegistrationCredTypeEnum {
  ADDRKEYHASH = "ADDR_KEYHASH",
  SCRIPTHASH = "SCRIPTHASH"
}
