/* tslint:disable */
/* eslint-disable */
/**
 * Yaci Store API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface DrepVoteThresholds
 */
export interface DrepVoteThresholds {
  /**
   * @type {number}
   * @memberof DrepVoteThresholds
   */
  dvtMotionNoConfidence?: number;

  /**
   * @type {number}
   * @memberof DrepVoteThresholds
   */
  dvtCommitteeNormal?: number;

  /**
   * @type {number}
   * @memberof DrepVoteThresholds
   */
  dvtCommitteeNoConfidence?: number;

  /**
   * @type {number}
   * @memberof DrepVoteThresholds
   */
  dvtUpdateToConstitution?: number;

  /**
   * @type {number}
   * @memberof DrepVoteThresholds
   */
  dvtHardForkInitiation?: number;

  /**
   * @type {number}
   * @memberof DrepVoteThresholds
   */
  dvtPpnetworkGroup?: number;

  /**
   * @type {number}
   * @memberof DrepVoteThresholds
   */
  dvtPpeconomicGroup?: number;

  /**
   * @type {number}
   * @memberof DrepVoteThresholds
   */
  dvtPptechnicalGroup?: number;

  /**
   * @type {number}
   * @memberof DrepVoteThresholds
   */
  dvtPpgovGroup?: number;

  /**
   * @type {number}
   * @memberof DrepVoteThresholds
   */
  dvtTreasuryWithdrawal?: number;
}
