/* tslint:disable */
/* eslint-disable */
/**
 * Yaci Store API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Epoch } from "./epoch";
/**
 *
 *
 * @export
 * @interface EpochsPage
 */
export interface EpochsPage {
  /**
   * @type {number}
   * @memberof EpochsPage
   */
  total?: number;

  /**
   * @type {number}
   * @memberof EpochsPage
   */
  totalPages?: number;

  /**
   * @type {Array<Epoch>}
   * @memberof EpochsPage
   */
  epochs?: Array<Epoch>;
}
