/* tslint:disable */
/* eslint-disable */
/**
 * Yaci Store API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface LocalDRepStakeDto
 */
export interface LocalDRepStakeDto {
  /**
   * @type {string}
   * @memberof LocalDRepStakeDto
   */
  drepHash?: string;

  /**
   * @type {string}
   * @memberof LocalDRepStakeDto
   */
  drepType?: LocalDRepStakeDtoDrepTypeEnum;

  /**
   * @type {number}
   * @memberof LocalDRepStakeDto
   */
  amount?: number;

  /**
   * @type {number}
   * @memberof LocalDRepStakeDto
   */
  epoch?: number;
}

/**
 * @export
 * @enum {string}
 */
export enum LocalDRepStakeDtoDrepTypeEnum {
  ADDRKEYHASH = "ADDR_KEYHASH",
  SCRIPTHASH = "SCRIPTHASH",
  ABSTAIN = "ABSTAIN",
  NOCONFIDENCE = "NO_CONFIDENCE"
}
