/* tslint:disable */
/* eslint-disable */
/**
 * Yaci Store API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { JsonNode } from "./json-node";
/**
 *
 *
 * @export
 * @interface MetadataLabelDto
 */
export interface MetadataLabelDto {
  /**
   * @type {number}
   * @memberof MetadataLabelDto
   */
  blockNumber?: number;

  /**
   * @type {number}
   * @memberof MetadataLabelDto
   */
  blockTime?: number;

  /**
   * @type {string}
   * @memberof MetadataLabelDto
   */
  txHash?: string;

  /**
   * @type {JsonNode}
   * @memberof MetadataLabelDto
   */
  jsonMetadata?: JsonNode;

  /**
   * @type {string}
   * @memberof MetadataLabelDto
   */
  cborMetadata?: string;

  /**
   * @type {number}
   * @memberof MetadataLabelDto
   */
  slot?: number;
}
