/* tslint:disable */
/* eslint-disable */
/**
 * Yaci Store API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface MoveInstataneousRewardSummary
 */
export interface MoveInstataneousRewardSummary {
  /**
   * @type {string}
   * @memberof MoveInstataneousRewardSummary
   */
  txHash?: string;

  /**
   * @type {number}
   * @memberof MoveInstataneousRewardSummary
   */
  slot?: number;

  /**
   * @type {number}
   * @memberof MoveInstataneousRewardSummary
   */
  blockNumber?: number;

  /**
   * @type {number}
   * @memberof MoveInstataneousRewardSummary
   */
  blockTime?: number;

  /**
   * @type {string}
   * @memberof MoveInstataneousRewardSummary
   */
  pot?: MoveInstataneousRewardSummaryPotEnum;

  /**
   * @type {number}
   * @memberof MoveInstataneousRewardSummary
   */
  certIndex?: number;

  /**
   * @type {number}
   * @memberof MoveInstataneousRewardSummary
   */
  totalStakeKeys?: number;

  /**
   * @type {number}
   * @memberof MoveInstataneousRewardSummary
   */
  totalRewards?: number;
}

/**
 * @export
 * @enum {string}
 */
export enum MoveInstataneousRewardSummaryPotEnum {
  RESERVES = "RESERVES",
  TREASURY = "TREASURY"
}
