/* tslint:disable */
/* eslint-disable */
/**
 * Yaci Store API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface PolicySupply
 */
export interface PolicySupply {
  /**
   * @type {string}
   * @memberof PolicySupply
   */
  policy?: string;

  /**
   * @type {number}
   * @memberof PolicySupply
   */
  supply?: number;
}
