/* tslint:disable */
/* eslint-disable */
/**
 * Yaci Store API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface PoolVotingThresholds
 */
export interface PoolVotingThresholds {
  /**
   * @type {number}
   * @memberof PoolVotingThresholds
   */
  pvtMotionNoConfidence?: number;

  /**
   * @type {number}
   * @memberof PoolVotingThresholds
   */
  pvtCommitteeNormal?: number;

  /**
   * @type {number}
   * @memberof PoolVotingThresholds
   */
  pvtCommitteeNoConfidence?: number;

  /**
   * @type {number}
   * @memberof PoolVotingThresholds
   */
  pvtHardForkInitiation?: number;

  /**
   * @type {number}
   * @memberof PoolVotingThresholds
   */
  pvtPpsecurityGroup?: number;
}
