/* tslint:disable */
/* eslint-disable */
/**
 * Yaci Store API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface PoolRetirement
 */
export interface PoolRetirement {
  /**
   * @type {number}
   * @memberof PoolRetirement
   */
  blockNumber?: number;

  /**
   * @type {number}
   * @memberof PoolRetirement
   */
  blockTime?: number;

  /**
   * @type {string}
   * @memberof PoolRetirement
   */
  txHash?: string;

  /**
   * @type {number}
   * @memberof PoolRetirement
   */
  certIndex?: number;

  /**
   * @type {string}
   * @memberof PoolRetirement
   */
  poolId?: string;

  /**
   * @type {number}
   * @memberof PoolRetirement
   */
  retirementEpoch?: number;

  /**
   * @type {number}
   * @memberof PoolRetirement
   */
  epoch?: number;

  /**
   * @type {number}
   * @memberof PoolRetirement
   */
  slot?: number;

  /**
   * @type {string}
   * @memberof PoolRetirement
   */
  blockHash?: string;

  /**
   * @type {string}
   * @memberof PoolRetirement
   */
  poolIdBech32?: string;
}
