/* tslint:disable */
/* eslint-disable */
/**
 * Yaci Store API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DrepVoteThresholds } from "./drep-vote-thresholds";
import { PoolVotingThresholds } from "./pool-voting-thresholds";
/**
 *
 *
 * @export
 * @interface ProtocolParams
 */
export interface ProtocolParams {
  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  minFeeA?: number;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  minFeeB?: number;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  maxBlockSize?: number;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  maxTxSize?: number;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  maxBlockHeaderSize?: number;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  keyDeposit?: number;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  poolDeposit?: number;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  maxEpoch?: number;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  poolPledgeInfluence?: number;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  expansionRate?: number;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  treasuryGrowthRate?: number;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  decentralisationParam?: number;

  /**
   * @type {string}
   * @memberof ProtocolParams
   */
  extraEntropy?: string;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  protocolMajorVer?: number;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  protocolMinorVer?: number;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  minUtxo?: number;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  minPoolCost?: number;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  adaPerUtxoByte?: number;

  /**
   * @type {{ [key: string]: Array<number>; }}
   * @memberof ProtocolParams
   */
  costModels?: { [key: string]: Array<number> };

  /**
   * @type {string}
   * @memberof ProtocolParams
   */
  costModelsHash?: string;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  priceMem?: number;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  priceStep?: number;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  maxTxExMem?: number;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  maxTxExSteps?: number;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  maxBlockExMem?: number;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  maxBlockExSteps?: number;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  maxValSize?: number;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  collateralPercent?: number;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  maxCollateralInputs?: number;

  /**
   * @type {PoolVotingThresholds}
   * @memberof ProtocolParams
   */
  poolVotingThresholds?: PoolVotingThresholds;

  /**
   * @type {DrepVoteThresholds}
   * @memberof ProtocolParams
   */
  drepVotingThresholds?: DrepVoteThresholds;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  committeeMinSize?: number;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  committeeMaxTermLength?: number;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  govActionLifetime?: number;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  govActionDeposit?: number;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  drepDeposit?: number;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  drepActivity?: number;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  minFeeRefScriptCostPerByte?: number;

  /**
   * @type {number}
   * @memberof ProtocolParams
   */
  nopt?: number;
}
