/* tslint:disable */
/* eslint-disable */
/**
 * Yaci Store API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface ProtocolParamsDto
 */
export interface ProtocolParamsDto {
  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  minFeeA?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  minFeeB?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  maxBlockSize?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  maxTxSize?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  maxBlockHeaderSize?: number;

  /**
   * @type {string}
   * @memberof ProtocolParamsDto
   */
  keyDeposit?: string;

  /**
   * @type {string}
   * @memberof ProtocolParamsDto
   */
  poolDeposit?: string;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  a0?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  rho?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  tau?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  decentralisationParam?: number;

  /**
   * @type {string}
   * @memberof ProtocolParamsDto
   */
  extraEntropy?: string;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  protocolMajorVer?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  protocolMinorVer?: number;

  /**
   * @type {string}
   * @memberof ProtocolParamsDto
   */
  minUtxo?: string;

  /**
   * @type {string}
   * @memberof ProtocolParamsDto
   */
  minPoolCost?: string;

  /**
   * @type {string}
   * @memberof ProtocolParamsDto
   */
  nonce?: string;

  /**
   * @type {{ [key: string]: { [key: string]: number; }; }}
   * @memberof ProtocolParamsDto
   */
  costModels?: { [key: string]: { [key: string]: number } };

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  priceMem?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  priceStep?: number;

  /**
   * @type {string}
   * @memberof ProtocolParamsDto
   */
  maxTxExMem?: string;

  /**
   * @type {string}
   * @memberof ProtocolParamsDto
   */
  maxTxExSteps?: string;

  /**
   * @type {string}
   * @memberof ProtocolParamsDto
   */
  maxBlockExMem?: string;

  /**
   * @type {string}
   * @memberof ProtocolParamsDto
   */
  maxBlockExSteps?: string;

  /**
   * @type {string}
   * @memberof ProtocolParamsDto
   */
  maxValSize?: string;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  collateralPercent?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  maxCollateralInputs?: number;

  /**
   * @type {string}
   * @memberof ProtocolParamsDto
   */
  coinsPerUtxoSize?: string;

  /**
   * @type {string}
   * @memberof ProtocolParamsDto
   */
  coinsPerUtxoWord?: string;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  pvtMotionNoConfidence?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  pvtCommitteeNormal?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  pvtCommitteeNoConfidence?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  pvtHardForkInitiation?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  dvtMotionNoConfidence?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  dvtCommitteeNormal?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  dvtCommitteeNoConfidence?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  dvtUpdateToConstitution?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  dvtHardForkInitiation?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  dvtPpnetworkGroup?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  dvtPpeconomicGroup?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  dvtPptechnicalGroup?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  dvtPpgovGroup?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  dvtTreasuryWithdrawal?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  committeeMinSize?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  committeeMaxTermLength?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  govActionLifetime?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  govActionDeposit?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  drepDeposit?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  drepActivity?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  minFeeRefScriptCostPerByte?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  eMax?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsDto
   */
  nOpt?: number;
}
