/* tslint:disable */
/* eslint-disable */
/**
 * Yaci Store API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ProtocolParams } from "./protocol-params";
/**
 *
 *
 * @export
 * @interface ProtocolParamsProposal
 */
export interface ProtocolParamsProposal {
  /**
   * @type {number}
   * @memberof ProtocolParamsProposal
   */
  blockNumber?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsProposal
   */
  blockTime?: number;

  /**
   * @type {string}
   * @memberof ProtocolParamsProposal
   */
  txHash?: string;

  /**
   * @type {string}
   * @memberof ProtocolParamsProposal
   */
  keyHash?: string;

  /**
   * @type {number}
   * @memberof ProtocolParamsProposal
   */
  targetEpoch?: number;

  /**
   * @type {ProtocolParams}
   * @memberof ProtocolParamsProposal
   */
  params?: ProtocolParams;

  /**
   * @type {number}
   * @memberof ProtocolParamsProposal
   */
  epoch?: number;

  /**
   * @type {number}
   * @memberof ProtocolParamsProposal
   */
  slot?: number;

  /**
   * @type {string}
   * @memberof ProtocolParamsProposal
   */
  era?: ProtocolParamsProposalEraEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum ProtocolParamsProposalEraEnum {
  Byron = "Byron",
  Shelley = "Shelley",
  Allegra = "Allegra",
  Mary = "Mary",
  Alonzo = "Alonzo",
  Babbage = "Babbage",
  Conway = "Conway"
}
