/* tslint:disable */
/* eslint-disable */
/**
 * Yaci Store API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface Relay
 */
export interface Relay {
  /**
   * @type {number}
   * @memberof Relay
   */
  port?: number;

  /**
   * @type {string}
   * @memberof Relay
   */
  ipv4?: string;

  /**
   * @type {string}
   * @memberof Relay
   */
  ipv6?: string;

  /**
   * @type {string}
   * @memberof Relay
   */
  dnsName?: string;
}
