/* tslint:disable */
/* eslint-disable */
/**
 * Yaci Store API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface ScriptDto
 */
export interface ScriptDto {
  /**
   * @type {string}
   * @memberof ScriptDto
   */
  scriptHash?: string;

  /**
   * @type {string}
   * @memberof ScriptDto
   */
  type?: ScriptDtoTypeEnum;

  /**
   * @type {number}
   * @memberof ScriptDto
   */
  serialisedSize?: number;
}

/**
 * @export
 * @enum {string}
 */
export enum ScriptDtoTypeEnum {
  Timelock = "timelock",
  PlutusV1 = "plutusV1",
  PlutusV2 = "plutusV2",
  PlutusV3 = "plutusV3"
}
