/* tslint:disable */
/* eslint-disable */
/**
 * Yaci Store API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface StakeAddressBalance
 */
export interface StakeAddressBalance {
  /**
   * @type {number}
   * @memberof StakeAddressBalance
   */
  blockNumber?: number;

  /**
   * @type {number}
   * @memberof StakeAddressBalance
   */
  blockTime?: number;

  /**
   * @type {string}
   * @memberof StakeAddressBalance
   */
  address?: string;

  /**
   * @type {number}
   * @memberof StakeAddressBalance
   */
  slot?: number;

  /**
   * @type {number}
   * @memberof StakeAddressBalance
   */
  quantity?: number;

  /**
   * @type {number}
   * @memberof StakeAddressBalance
   */
  epoch?: number;
}
