/* tslint:disable */
/* eslint-disable */
/**
 * Yaci Store API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface TxAsset
 */
export interface TxAsset {
  /**
   * @type {number}
   * @memberof TxAsset
   */
  blockNumber?: number;

  /**
   * @type {number}
   * @memberof TxAsset
   */
  blockTime?: number;

  /**
   * @type {number}
   * @memberof TxAsset
   */
  slot?: number;

  /**
   * @type {string}
   * @memberof TxAsset
   */
  txHash?: string;

  /**
   * @type {string}
   * @memberof TxAsset
   */
  policy?: string;

  /**
   * @type {string}
   * @memberof TxAsset
   */
  assetName?: string;

  /**
   * @type {string}
   * @memberof TxAsset
   */
  unit?: string;

  /**
   * @type {string}
   * @memberof TxAsset
   */
  fingerprint?: string;

  /**
   * @type {number}
   * @memberof TxAsset
   */
  quantity?: number;

  /**
   * @type {string}
   * @memberof TxAsset
   */
  mintType?: TxAssetMintTypeEnum;
}

/**
 * @export
 * @enum {string}
 */
export enum TxAssetMintTypeEnum {
  MINT = "MINT",
  BURN = "BURN"
}
