/* tslint:disable */
/* eslint-disable */
/**
 * Yaci Store API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Redeemer } from "./redeemer";
/**
 *
 *
 * @export
 * @interface TxContractDetails
 */
export interface TxContractDetails {
  /**
   * @type {string}
   * @memberof TxContractDetails
   */
  txHash?: string;

  /**
   * @type {string}
   * @memberof TxContractDetails
   */
  scriptHash?: string;

  /**
   * @type {string}
   * @memberof TxContractDetails
   */
  scriptContent?: string;

  /**
   * @type {string}
   * @memberof TxContractDetails
   */
  type?: TxContractDetailsTypeEnum;

  /**
   * @type {Redeemer}
   * @memberof TxContractDetails
   */
  redeemer?: Redeemer;

  /**
   * @type {string}
   * @memberof TxContractDetails
   */
  datum?: string;

  /**
   * @type {string}
   * @memberof TxContractDetails
   */
  datumHash?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum TxContractDetailsTypeEnum {
  NATIVESCRIPT = "NATIVE_SCRIPT",
  PLUTUSV1 = "PLUTUS_V1",
  PLUTUSV2 = "PLUTUS_V2",
  PLUTUSV3 = "PLUTUS_V3"
}
