/* tslint:disable */
/* eslint-disable */
/**
 * Yaci Store API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { TxUtxo } from "./tx-utxo";
/**
 *
 *
 * @export
 * @interface TxInputsOutputs
 */
export interface TxInputsOutputs {
  /**
   * @type {string}
   * @memberof TxInputsOutputs
   */
  hash?: string;

  /**
   * @type {Array<TxUtxo>}
   * @memberof TxInputsOutputs
   */
  inputs?: Array<TxUtxo>;

  /**
   * @type {Array<TxUtxo>}
   * @memberof TxInputsOutputs
   */
  outputs?: Array<TxUtxo>;
}
