/* tslint:disable */
/* eslint-disable */
/**
 * Yaci Store API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface TxMetadataLabelCBORDto
 */
export interface TxMetadataLabelCBORDto {
  /**
   * @type {number}
   * @memberof TxMetadataLabelCBORDto
   */
  blockNumber?: number;

  /**
   * @type {number}
   * @memberof TxMetadataLabelCBORDto
   */
  blockTime?: number;

  /**
   * @type {string}
   * @memberof TxMetadataLabelCBORDto
   */
  label?: string;

  /**
   * @type {string}
   * @memberof TxMetadataLabelCBORDto
   */
  metadata?: string;

  /**
   * @type {number}
   * @memberof TxMetadataLabelCBORDto
   */
  slot?: number;
}
