/* tslint:disable */
/* eslint-disable */
/**
 * Yaci Store API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Amt } from "./amt";
/**
 *
 *
 * @export
 * @interface TxOuput
 */
export interface TxOuput {
  /**
   * @type {string}
   * @memberof TxOuput
   */
  address?: string;

  /**
   * @type {Array<Amt>}
   * @memberof TxOuput
   */
  amounts?: Array<Amt>;

  /**
   * @type {string}
   * @memberof TxOuput
   */
  dataHash?: string;

  /**
   * @type {string}
   * @memberof TxOuput
   */
  inlineDatum?: string;

  /**
   * @type {string}
   * @memberof TxOuput
   */
  referenceScriptHash?: string;
}
