/* tslint:disable */
/* eslint-disable */
/**
 * Yaci Store API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 *
 *
 * @export
 * @interface TxRedeemerDto
 */
export interface TxRedeemerDto {
  /**
   * @type {number}
   * @memberof TxRedeemerDto
   */
  txIndex?: number;

  /**
   * @type {string}
   * @memberof TxRedeemerDto
   */
  purpose?: string;

  /**
   * @type {string}
   * @memberof TxRedeemerDto
   */
  scriptHash?: string;

  /**
   * @type {string}
   * @memberof TxRedeemerDto
   */
  datumHash?: string;

  /**
   * @type {string}
   * @memberof TxRedeemerDto
   */
  redeemerDataHash?: string;

  /**
   * @type {string}
   * @memberof TxRedeemerDto
   */
  unitMem?: string;

  /**
   * @type {string}
   * @memberof TxRedeemerDto
   */
  unitSteps?: string;
}
