name: Run Smoke Tests on Staging Environment
on:
  workflow_dispatch:

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v3

      - name: 🦾 Create .env file
        run: |
          echo "PORT=3000" > .env
          echo "REACT_APP_VERSION=$npm_package_version" >> .env
          echo "REACT_APP_API_URL=${{ secrets.EXPLORER_API_MAINNET_URL }}" >> .env
          echo "REACT_APP_MAINNET_APP_URL=${{ secrets.EXPLORER_API_MAINNET_URL }}" >> .env
          echo 'REACT_APP_NETWORK_NAMES="{"mainnet":"Mainnet","preprod":"Preprod"}"' >> .env
          echo "REACT_APP_MAINNET_API_URL=${{ secrets.EXPLORER_API_MAINNET_URL }}" >> .env
          echo "REACT_APP_AUTH_API_URL=${{ secrets.EXPLORER_AUTH_API_URL }}" >> .env
          echo "REACT_APP_NETWORK=mainnet" >> .env
          echo "REACT_APP_JSD_WIDGET_KEY=${{ secrets.EXPLORER_JSD_WIDGET_KEY }}" >> .env

      - name: 🫡 Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: 🧘‍♀️ Download dependencies
        run: npm ci

      - name: Generate test script
        run: |
          cd cypress/smoke
          which pip || ( sudo apt update -qq && sudo apt install -y python3-pip )
          pip3 install numpy requests
          python3 CypressDynamicScript.py

      - name: 🏂 Install serve globally
        run: npm install -g serve

      - name: 🚧 Build the project
        run: npm run build

      - name: 👻 Add empty env.global.js file
        run: touch build/static/js/env.global.js

      - name: 🎳 Run tests
        uses: cypress-io/github-action@v6
        with:
          start: serve -s build -L
          wait-on: "http://localhost:3000"
          wait-on-timeout: 360

      - name: 📹 Archive test videos
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: videos
          path: ./cypress/videos

      - name: 🖼️ Archive test screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: screenshots
          path: ./cypress/screenshots
